CXX = g++
CXXFLAGS = -std=c++11 -Wall

all: problem1 problem2 problem3

problem1: problem1.cpp
	$(CXX) $(CXXFLAGS) -o problem1 problem1.cpp

problem2: problem2.cpp
	$(CXX) $(CXXFLAGS) -o problem2 problem2.cpp

problem3: problem3.cpp
	$(CXX) $(CXXFLAGS) -o problem3 problem3.cpp

clean:
	rm -f problem1 problem2
